### ISSUE TITLE
Lab 1 - Typo in the value of the OCP_PASSWD environment variable

### ISSUE THREAD

**Issue by honghuac** [redhat-gpe/rhte_lab_06_operational_intelligence#11]
There is a *\* slash symbol in the value of the OCP_PASSWD environment variable, which is a causing a login error.

**Comment by honghuac** [comment]
Addressed.

**Comment by jeffreydelong** [comment]
this instruction in Lab 1 3.1
echo "export OCP_PASSWD=r3dh4t1!" >> ~/.bashrc
-bash: !": event not found

Is this the result of this being changed?

**Comment by honghuac** [comment]
@jeffreydelong I have updated the password - f812a3e2d4b2e3dbc8e7ac3ca2294a58ebfa1f13. Please retest.
