### ISSUE TITLE
oc get KafkaTopic returns no resources found

### ISSUE THREAD

**Issue by jeffreydelong** [redhat-gpe/rhte_lab_06_operational_intelligence#13]
[lab-user@clientvm 0 ~]$ sudo -i
[root@clientvm 0 ~]# oc get KafkaTopic
No resources found.
[root@clientvm 0 ~]#

**Comment by jeffreydelong** [comment]
This is on clientvm.f45c.rhte.opentlc.com

**Comment by nandanj** [comment]
$ sudo -i
[root@clientvm 0 ~]# oc get KafkaTopics
NAME         AGE
my-topic     19h
my-topic-2   19h

I'll change to plural

**Comment by Pkrish15** [comment]
[root@clientvm 0 ~]# oc get KafkaTopic
NAME         AGE
my-topic     7d
my-topic-2   7d
[root@clientvm 0 ~]# oc get KafkaTopics
NAME         AGE
my-topic     7d
my-topic-2   7d

Both the commands works as a root user. 

Hence closing this issue.
