### ISSUE TITLE
Login to cluster 

### ISSUE THREAD

**Issue by jeffreydelong** [redhat-gpe/rhte_lab_06_operational_intelligence#19]
Lab 2 3.2 Instruction 1 says
Log into OpenShift Environment using OC Client Tool to your Lab Region

oc login https://master.$REGION.openshift.opentlc.com -u $OCP_USERNAME -p $OCP_PASSWD

This is incorrect, it should be
oc login https://$HOSTNAME:8443 -u $OCP_USERNAME -p $OCP_PASSWD

**Comment by Pkrish15** [comment]
Fixed in the New Build
