### ISSUE TITLE
Lab 2 4.3 Instruction 4ii - oc get pods 

### ISSUE THREAD

**Issue by jeffreydelong** [redhat-gpe/rhte_lab_06_operational_intelligence#20]
has more PODs than in the instructions, e.g.,

[lab-user@clientvm 0 ~/lab/operational_intelligence/uber-data-analysis master ⭑|✔]$ oc get pods -w
NAME                          READY     STATUS    RESTARTS   AGE
apache-zeppelin-1-build       1/1       Running   0          14s
oshinko-web-1-kvqqn           2/2       Running   0          9m
uber-data-cluster-m-2-d6gp7   1/1       Running   0          3m
uber-data-cluster-w-2-s54sz   1/1       Running   0          2m
apache-zeppelin-1-deploy   0/1       Pending   0         0s
apache-zeppelin-1-deploy   0/1       Pending   0         0s
apache-zeppelin-1-deploy   0/1       ContainerCreating   0         0s
apache-zeppelin-1-build   0/1       Completed   0         2m
apache-zeppelin-1-9v99v   0/1       Pending   0         0s
apache-zeppelin-1-9v99v   0/1       Pending   0         0s
apache-zeppelin-1-9v99v   0/1       ContainerCreating   0         0s
apache-zeppelin-1-deploy   1/1       Running   0         1s
apache-zeppelin-1-9v99v   1/1       Running   0         1s
apache-zeppelin-1-deploy   0/1       Completed   0         3s
apache-zeppelin-1-deploy   0/1       Terminating   0         3s
apache-zeppelin-1-deploy   0/1       Terminating   0         3s

**Comment by Pkrish15** [comment]
In total it should have only 5 Pods running. This has been addressed now.

**Comment by Pkrish15** [comment]
Fixed in the new build
