### ISSUE TITLE
lab 2 5.5.c Changing data directory

### ISSUE THREAD

**Issue by jeffreydelong** [redhat-gpe/rhte_lab_06_operational_intelligence#21]
Instructions says

You can change the directory structure in zeppelin notebook pointing to the data directory in POD

But does not specify how to do this.

**Comment by Pkrish15** [comment]
Since All Paragraph's in Zeppelin are Editable, Screen Shot has been to show the change in the Directory Structure.

**Comment by Pkrish15** [comment]
Fixed
