### ISSUE TITLE
01_kafka_injest: html rendering is not correct

### ISSUE THREAD

**Issue by jbride** [redhat-gpe/rhte_lab_06_operational_intelligence#6]
There are formatting errors and inconsistencies in the asciidoc of this lab instruction such that entire steps are being omitted when viewed in opentlc.com/rhte   (and corresponding jenkins job).

**Comment by Pkrish15** [comment]
Formatting inconsistencies have been taken care and HTML rending is perfect now.
http://www.opentlc.com/rhte/rhte_lab_06_operational_intelligence/01_kafka_ingest_and_publish/01_kafka_ingest_and_publish_Lab.html
