### ISSUE TITLE
01_kafka_inject:  deployment.yml

### ISSUE THREAD

**Issue by jbride** [redhat-gpe/rhte_lab_06_operational_intelligence#7]
1)  instructions should provide a command that creates the deployment.yml on the student's lab environment (ie:  in $HOME/lab) .  Otherwise, this file could be included in the lab assets that the student just previously cloned.

2)  There needs to be elaboration as to the contents of this deployment.yml .
     What are these products and consumers suppose to connect to ?
     Where do I find the list of possible environment variables for these producers and consumers ?
      What ports and transports are going to be utilized ?
      What security mechanisms are involved ?
      A deployment topology diagram is always helpful.

3)  The producer and consumer images point reference an image repository that is neither tagged nor does GPTE control.  This will result in random unexpected problems.  Our team has an organization in [dockhub ](https://hub.docker.com/u/rhtgptetraining/)that can be utilized.  We can also create one in quay if that is preferable.

4)  The name of the producer and consumer images have a name of _helloworld_.  Are there engineering releases that we should be using ?

5)  The names of the OCP resources in this file should reflect the business use case.  "kafka-producer" is likely too generic.   A production environment would have a more representative name of its purpose and how it fits into the solution architecture.

**Comment by Pkrish15** [comment]
Linking this issue, with https://github.com/redhat-gpe/rhte_lab_06_operational_intelligence/issues/23.

Once I complete the issue 23, this will be taken care.

**Comment by Pkrish15** [comment]
Already made changes and provided a reference commit to this changes.

Issue #23 is closed, Hence closing this issue.
